"""Export real ingested Premier League data (+ live predictions, if generated)
to static JSON for the web app.

Reads data/oasis.sqlite (populated by ingest_fixtures.py) and, if present,
outputs/predictions.json (generated by predict.py) and writes
web/src/data/premier-league.json. A fixture with no matching prediction gets
`prediction: null` -- the web app renders an honest "not yet published"
state for those rather than fabricating probabilities.

Run after re-ingesting / re-predicting, before `npm run build`:

    python3 src/predict.py               # optional: refresh predictions first
    python3 src/export_web_data.py
"""

import json
from pathlib import Path

import db
from elo import EloRatings

PL_LEAGUE_ID = 39
REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "web" / "src" / "data" / "premier-league.json"
PREDICTIONS_PATH = REPO_ROOT / "outputs" / "predictions.json"

DECIDED_STATUSES = ("FT", "AET", "PEN")


def compute_elo(conn) -> dict[int, float]:
    """Replay every decided PL fixture chronologically through the project's
    own Elo engine (src/elo.py) to get each team's current rating."""
    ratings = EloRatings()
    rows = conn.execute(
        """
        SELECT home_team_id, away_team_id, home_goals, away_goals
        FROM fixtures
        WHERE league_id = ? AND status_short IN (?, ?, ?)
        ORDER BY kickoff_utc ASC
        """,
        (PL_LEAGUE_ID, *DECIDED_STATUSES),
    ).fetchall()
    for row in rows:
        ratings.update(row["home_team_id"], row["away_team_id"], row["home_goals"], row["away_goals"], neutral=False)
    return {team_id: round(elo) for team_id, elo in ratings.ratings.items()}


def current_season(conn) -> int:
    row = conn.execute(
        "SELECT MAX(season) AS s FROM fixtures WHERE league_id = ? AND status_short = 'NS'",
        (PL_LEAGUE_ID,),
    ).fetchone()
    return row["s"]


def team_names(conn) -> dict[int, str]:
    rows = conn.execute("SELECT team_id, name FROM teams").fetchall()
    return {row["team_id"]: row["name"] for row in rows}


def compute_standings(conn, season: int, names: dict[int, str], elo: dict[int, float]) -> list[dict]:
    rows = conn.execute(
        """
        SELECT home_team_id, away_team_id, home_goals, away_goals
        FROM fixtures
        WHERE league_id = ? AND season = ? AND status_short IN (?, ?, ?)
        """,
        (PL_LEAGUE_ID, season, *DECIDED_STATUSES),
    ).fetchall()

    table: dict[int, dict] = {}

    def row_for(team_id: int) -> dict:
        return table.setdefault(
            team_id,
            {"team_id": team_id, "played": 0, "won": 0, "drawn": 0, "lost": 0, "goals_for": 0, "goals_against": 0},
        )

    for r in rows:
        home, away = row_for(r["home_team_id"]), row_for(r["away_team_id"])
        home["played"] += 1
        away["played"] += 1
        home["goals_for"] += r["home_goals"]
        home["goals_against"] += r["away_goals"]
        away["goals_for"] += r["away_goals"]
        away["goals_against"] += r["home_goals"]
        if r["home_goals"] > r["away_goals"]:
            home["won"] += 1
            away["lost"] += 1
        elif r["home_goals"] < r["away_goals"]:
            away["won"] += 1
            home["lost"] += 1
        else:
            home["drawn"] += 1
            away["drawn"] += 1

    standings = []
    for team_id, t in table.items():
        goal_diff = t["goals_for"] - t["goals_against"]
        points = t["won"] * 3 + t["drawn"]
        standings.append(
            {
                "teamId": team_id,
                "team": names.get(team_id, f"Team {team_id}"),
                "played": t["played"],
                "won": t["won"],
                "drawn": t["drawn"],
                "lost": t["lost"],
                "goalDiff": goal_diff,
                "points": points,
                "elo": elo.get(team_id),
            }
        )
    standings.sort(key=lambda t: (-t["points"], -t["goalDiff"], -t["won"]))
    return standings


def recent_form(conn, team_id: int, before_season: int, limit: int = 5) -> list[str]:
    rows = conn.execute(
        """
        SELECT home_team_id, away_team_id, home_goals, away_goals, kickoff_utc
        FROM fixtures
        WHERE league_id = ? AND status_short IN (?, ?, ?)
          AND (home_team_id = ? OR away_team_id = ?)
        ORDER BY kickoff_utc DESC LIMIT ?
        """,
        (PL_LEAGUE_ID, *DECIDED_STATUSES, team_id, team_id, limit),
    ).fetchall()
    form = []
    for r in rows:
        is_home = r["home_team_id"] == team_id
        gf = r["home_goals"] if is_home else r["away_goals"]
        ga = r["away_goals"] if is_home else r["home_goals"]
        form.append("W" if gf > ga else "L" if gf < ga else "D")
    return list(reversed(form))


def next_matchday_fixtures(conn, season: int, names: dict[int, str]) -> tuple[str, list[dict]]:
    earliest = conn.execute(
        """
        SELECT round FROM fixtures
        WHERE league_id = ? AND season = ? AND status_short = 'NS'
        ORDER BY kickoff_utc ASC LIMIT 1
        """,
        (PL_LEAGUE_ID, season),
    ).fetchone()
    if earliest is None:
        return "", []
    round_name = earliest["round"]

    rows = conn.execute(
        """
        SELECT fixture_id, kickoff_utc, round, status_short, home_team_id, away_team_id,
               venue_name, venue_city, referee
        FROM fixtures
        WHERE league_id = ? AND season = ? AND round = ?
        ORDER BY kickoff_utc ASC
        """,
        (PL_LEAGUE_ID, season, round_name),
    ).fetchall()

    fixtures = []
    for r in rows:
        fixtures.append(
            {
                "id": r["fixture_id"],
                "kickoffUtc": r["kickoff_utc"],
                "round": r["round"],
                "status": r["status_short"],
                "homeTeamId": r["home_team_id"],
                "awayTeamId": r["away_team_id"],
                "home": names.get(r["home_team_id"], f"Team {r['home_team_id']}"),
                "away": names.get(r["away_team_id"], f"Team {r['away_team_id']}"),
                "venueName": r["venue_name"],
                "venueCity": r["venue_city"],
                "referee": r["referee"],
            }
        )
    return round_name, fixtures


def load_predictions() -> dict:
    if not PREDICTIONS_PATH.exists():
        return {"model": None, "generatedAt": None, "byFixtureId": {}}
    raw = json.loads(PREDICTIONS_PATH.read_text())
    by_id = {}
    for p in raw.get("predictions", []):
        by_id[p["fixture_id"]] = {
            "pHome": p["p_home"],
            "pDraw": p["p_draw"],
            "pAway": p["p_away"],
            "marketPHome": p["market_p_home"],
            "likelyScore": p["likely_score"],
            "expectedGoals": p["expected_goals"],
            "over25": p["over_2_5"],
            "btts": p["btts"],
            "confidence": p["confidence"],
            "why": p["why"],
            "stage": p["stage"],
        }
    return {
        "model": raw.get("model"),
        "generatedAt": raw.get("generated_at"),
        "byFixtureId": by_id,
    }


def data_freshness(conn) -> str:
    row = conn.execute(
        "SELECT MAX(updated_at) AS ts FROM fixtures WHERE league_id = ?",
        (PL_LEAGUE_ID,),
    ).fetchone()
    return row["ts"]


def main() -> None:
    conn = db.get_connection()
    season = current_season(conn)
    names = team_names(conn)
    elo = compute_elo(conn)
    round_name, fixtures = next_matchday_fixtures(conn, season, names)

    # The upcoming season has no decided fixtures yet before matchday 1 --
    # fall back to the last completed season's final table rather than
    # showing an all-zero standings grid.
    standings = compute_standings(conn, season, names, elo)
    standings_season = season
    if not standings:
        standings_season = season - 1
        standings = compute_standings(conn, standings_season, names, elo)

    predictions = load_predictions()

    fixtures_with_form = []
    for f in fixtures:
        fixtures_with_form.append(
            {
                **f,
                "homeForm": recent_form(conn, f["homeTeamId"], season),
                "awayForm": recent_form(conn, f["awayTeamId"], season),
                "prediction": predictions["byFixtureId"].get(f["id"]),
            }
        )

    payload = {
        "leagueId": PL_LEAGUE_ID,
        "leagueName": "Premier League",
        "season": season,
        "generatedAt": data_freshness(conn),
        "nextRound": round_name,
        "fixtures": fixtures_with_form,
        "standings": standings,
        "standingsSeason": standings_season,
        "standingsIsFinal": standings_season != season,
        "predictionModel": predictions["model"],
        "predictionsGeneratedAt": predictions["generatedAt"],
    }

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(json.dumps(payload, indent=2, ensure_ascii=False))
    predicted_count = sum(1 for f in fixtures_with_form if f["prediction"] is not None)
    print(
        f"Wrote {len(fixtures_with_form)} fixtures ({predicted_count} with predictions), "
        f"{len(standings)} standings rows -> {OUTPUT_PATH}"
    )


if __name__ == "__main__":
    main()
